<a href="https://colab.research.google.com/github/marcellamj/soulcode-martech/blob/main/AD2_Fundamentos_de_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundamentos de Python**

Escola: SoulCode Academy

Curso: Bootcamp Analista de Dados - Martech AD2

Período: Semana 4

Professor: Franciane Rodrigues/Douglas Ribeiro

*  **Lógica de Programação**: é a estruturação de conceitos e regras que orientam a execução do algoritmo

*  **Algoritmo**: é a receita, ou seja, os comandos em um passo claro e lógico que conduzem as ações para a resolução de um problema ou para atingir determinado objetivo.

*  **Programa**: é a implementação do algoritmo.

*  **Script** é um conjunto de instruções ou comandos escritos em uma linguagem de programação específica. Geralmente, os scripts são usados para automatizar tarefas ou para definir o comportamento de um programa ou sistema. Eles são frequentemente executados interpreta

## **Comentários e Tipos básicos de Dados**

In [ ]:
print('Olá')

Olá

In [ ]:
#Tipos de Dados

![Foto 1.png]()

In [ ]:
# Estamos escrevendo nossos dados pessoais
print(28)               # int - quant
print(1.63)             # float - quant
print('Marcella')       # str escrita com aspas simples - quali
print("Macedo")         # str com aspas duplas - quali
print(False)            # bool - quali (dummy/binária)

28
1.63
Marcella
Macedo
False

**RESUMO**

*   Os **comentários** são como notas que você deixa para que você ou outra pessoa possa ler e ajuda documentar o seu código
*   **Comando print:** é uma função de saída utilizada em várias linguagens de
programação para exibir mensagens ou valores na tela do computador.
*   **\n**: usado para criar quebras de linha em um texto
*   Tipos de dados no Python mais usados são int, float, str, bool
*   **int e float:** dados quantitativos
*   **str:** dados categóricos

## **Variáveis**

In [ ]:
# Declarando as variáveis
idade=28
altura=1.63
nome='Marcella'
sobrenome="Macedo"
filhos=False

In [ ]:
# Estamos escrevendo nossos dados pessoais
print(idade)             # int - quant
print(altura)            # float - quant
print(nome)              # str escrita com aspas simples - quali
print(sobrenome)         # str com aspas duplas - quali
print(filhos)             # bool - quali (dummy/binária)

28
1.63
Marcella
Macedo
False

In [ ]:
# Comando type serve para checar o tipo de dado declarado na variável
type(idade)

int

In [ ]:
# Checando o tipo de variável usando comandos print e type juntos
print(type(idade))
print(type(altura))
print(type(nome))
print(type(sobrenome))
print(type(filhos))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>

In [ ]:
# Armazenando strings e número
nome_completo='Marcella Macedo'
numero_favorito="13"

In [ ]:
# Se o número estiver entre aspas ele se transforma numa string
print(nome_completo, numero_favorito)

Marcella Macedo 13

**Resumo**
*  **Variáveis** permitem salvar valores na memória usando um nome que atribuímos
* Declaramos um nome no lado esquerdo do operador igual (“=”), e no lado direito, atribuir o valor que queremos salvar para usar mais tarde.
* Como ler: Declaramos a variável "a" ao valor do "2" do tipo int
* Como ler: Declaramos a variável "b" ao valor do "10.953" do tipo float
* Como ler: A variável "a" recebe valor 2 do tipo int
* Como ler: A variável "b" recebe valor 10.953 do tipo float
* É possível usar os dois comandos print e type juntos
* **Atenção**: Número pode ser string

**Regras para nomes de variáveis**
* Deve começar com uma letra (maíuscula ou minúscula) ou subcrito(_).
* Nunca pode começar com um número.
* Pode conter letras maiúsculas, minúsculas, números e subscrito.
* Não pode-se utilizar como parte do nome de uma variável:
{ ( + - * / \ ; . , ?
* Letras maiúsculas e minúsculas são diferentes:
casa = 4
Casa = 3

### **Conversão de Variáveis**

In [ ]:
# Conversão de int para float

num_int=10
num_float=float(num_int)

In [ ]:
#Checando a conversão

print(type(num_int), type(num_float))
print(num_float)

<class 'int'> <class 'float'>
10.0

In [ ]:
# Conversão de int para string
num_int=10
num_str=str(num_int)

In [ ]:
# Checando a conversão
print(type(num_int), type(num_str))
print(num_str)

<class 'int'> <class 'str'>
10

In [ ]:
# Conversão de float para int
num_float=10.5
num_int=int(num_float)

In [ ]:
# Checando a conversão
print(type(num_float),type(num_int))
print(num_int)

<class 'float'> <class 'int'>
10

In [ ]:
# Conversão de float para str
num_float=10.5
num_str=str(num_float)

In [ ]:
# Conversão de str para int
num_str='13'
num_int=int(num_str)

In [ ]:
# Conversão de str para float
num_str='13.4'
num_float=float(num_str)

In [ ]:
# Checando
print(type(num_str),type(num_float))
print(num_float)

<class 'str'> <class 'float'>
13.4

## **Operadores**

## **Operadores Matemáticos**

Os operadores matemáticos básicos, tais como: adição, subtração, multiplicação, divisão, exponenciação e radiciação podem ser feitos dentro do Python.

#![Foto 4.png]()

In [ ]:
# Adição
n1=5.887
n2=7.15
soma=n1+n2

print(soma)
print('A soma é:',soma)
print(f'A soma é {soma:.2f}')

13.036999999999999
A soma é: 13.036999999999999
A soma é 13.04

In [ ]:
# Subtração
a1=154.587
a2=10.548
sub=a1-a2

print(sub)
print('A subtração é:', round(sub,2))
print(f"A subtração é {round(sub)}.")
print(a1-a2)
a1-a2

144.039
A subtração é: 144.04
A subtração é 144.
144.039

144.039

In [ ]:
# Multiplicação
m1=5
m2=8
mult=m1*m2

print(mult)
print('A multiplicação é:', round(mult,2))
print(f'A multiplicação é {mult:.2f}')
print(m1*m2)
m1*m2

40
A multiplicação é: 40
A multiplicação é 40.00
40

40

In [ ]:
# Divisão
x1=10
x2=5
div=x1/x2

print(div)
print('A divisão é:', round(div,2))
print(f'A divisão é {div:.2f}')
print(x1/x2)

2.0
A divisão é: 2.0
A divisão é 2.00
2.0

In [ ]:
# Exponenciação
x1=10
x2=5
pot=x1**x2

print(div)
print('A pot é:', round(div,2))
print(f'A pot é {div:.2f}')
print(x1/x2)

2.0
A pot é: 2.0
A pot é 2.00
2.0

In [ ]:
# Radiciação
x1=9
rad=x1**1/2

print(rad)
print('A rad é:', round(rad,2))
print(f'A rad é {rad:.2f}')
print()

4.5
A rad é: 4.5
A rad é 4.50



![Foto 2.png]()

![Foto 3.png]()

## **Aula 14 - Douglas**

In [ ]:
# Resumo Operadores matemáticos

soma=1+2
sub=3-2
mult=2*2
div=10/2
pot=5**2
rad=25**(1/2) #radiciação com fração
rad2=49**0,5  #radiciação com decimal
idiv=3//2     #parte inteira da divisão
rdiv=3%2      #resto da divisão

In [ ]:
# Melhorando o visual dos prints com f-string

print(f'A soma dos números é: {soma}')
print(f'A subtração dos números é: {sub}')
print(f'A multiplicação dos números é:{mult}')
print(f'A divisão dos números é:{div}')
print(f'A potência dos números é:{pot}')
print(f'A raiz quadrada do número é:{rad}')
print(f'A raiz quadrada do número é:{rad2}')
print(f'O resto da divisão é:{rdiv}')

A soma dos números é: 3
A subtração dos números é: 1
A multiplicação dos números é:4
A divisão dos números é:5.0
A potência dos números é:25
A raiz quadrada do número é:5.0
A raiz quadrada do número é:(1, 5)
O resto da divisão é:1

### **Operadores de Comparação (booleanos)**

In [ ]:
# (==) Comparação de Igualdade

a = 3       #int
b = 3.0     #float
teste1 = a == b
print(teste1)

teste2 = "douglas" == "Douglas"
print(teste2)

True
False

In [ ]:
# (!=) Comparação de Diferença

a = 5       #int
b = 3.0     #float
teste1 = a  == b
print(teste1)

teste2 = "douglas" == "Douglas"
print(teste2)

False
False

In [ ]:
# (>,<,>=,<=) Comparação de Maior/Menor/Maior ou igual/Menor ou igual

a = 5       #int
b = 3.0     #float
teste1 = a>b
print(teste1)

teste2 = "douglas"=="Douglas"
print(teste2)

teste3= a!=b
print(teste3)

teste4= a<=b
print(teste4)

True
False
True
False

###**Operadores de Atribuição**

In [ ]:
# Atribuição direta

nome='João'
altura=1.63

# Atribuição de soma (+=) equivale a x=x+y (uma variável x que existe recebendo ela mesma + outro valor)
# Exemplo: crie uma variável t que receba o número 3 e some 1
q=3
q += 1
print(f'O resultado da soma é {q}.')

In [ ]:
# Atribuição de subtração (-=) equivale a x=x-y
r=5
r -= 2
print(f'O resultado da sub é {r}.')

O resultado da sub é 3.

In [ ]:
# Atribuição de multiplicação (*=)
s = 5
s *= 2
print(f'O resultado da mult é {s}.')

# Atribuição de divisão (/=)
t = 7
t /= 2
print(f'O resultado da div é {t}.')

# Atribuição da parte inteira de divisão (//=)
u=7
u //= 2
print(f'O resultado de u//2 é {u}.')

# Atribuição da resto de divisão (%=)
v=7
v %= 2
print(f'O resto da divisão é {v}.')

# Atribuição da potenciação (**=)
w=7
w **= 2
print(f'O resultado da potência de w é {w}.')

O resultado da mult é 10.
O resultado da div é 3.5.
O resultado de u//2 é 3.
O resto da divisão é 1.
O resultado da potência de w é 49.

### **Operadores lógicos**

In [ ]:
# (and) retorna verdadeiro se todas as afirmações forem verdadeiras
teste8 = 3!=2 and 3>=2 and 3<4
print(teste8)

teste9 = (3!=2) & (3<=2) & (3<4)
print(teste9)

# (or) retorna verdadeiro se pelo menos uma é verdadeira
teste10=3>=2 or 3!=2 or 3>4
print(teste10)

# (not) inverte verdadeiro com falso ou vice-versa
teste11= not(teste10)
print(teste11)

teste12= not(teste9)
print(teste12)

teste13 = (3<=2) & (3!=2) & (3<4)
#           F        V        V
print(teste13)

True
False
True
False
True
False

### **Operadores de Identidade (is, is not, in, not in)**

In [ ]:
# (is) compara se objeto é igual ao outro em valor e tipo de variável
p=3
h=3.0
teste16=p==h
print(f'p==h é: {teste16}')

teste17= p is h
print(f'p is h: {teste17}')
print(type(p))
print(type(h))

# (is not) compara se são diferentes em valor e tipo
m=8
n=8.0
teste18= m is not n
print(f'm is not n: {teste18}')

p==h é: True
p is h: False
<class 'int'>
<class 'float'>
m is not n: True

In [ ]:
# (in) Retorna verdadeiro se um caracter ou sequência de caracteres for encontrada dentro de uma string
nome ='Marcella'
teste19= 'cela' in nome
print(f'Marcella contém cela: {teste19}')

# (not in) Retorna verdadeiro se um caracter ou sequência NÃO for encontrado dentro de uma string
teste20= 'mar' not in nome
print(f'Marcella não contém mar: {teste20}')

Marcella contém cela: False
Marcella não contém mar: True

### **Coletando infos do usuário**

In [ ]:
nome=input('Seu nome: ')
print(f'O nome é: {nome}.')
peso=int(input('Informe seu peso em kg: '))
print(f'Você pesa {peso} kg.')
altura=float(input('Sua altura em metros: '))
print(f'Altura é: {altura}')
imc=peso/altura**2
print(f'IMC é:{imc:.1f}')

## **Strings**

### **Índice e Ordinais**

In [ ]:
# 0 1 2 3 4 5 6 7 8 9 10 11 12 13
# d o u g @ g m a i l . c o m
email='doug@gmail.com'

# encontrando um caracter pelo índice
# qual é o quinto caracter dessa string?
print(f'o quinto caracter é: {email[4]}')
# qual é o último caracter?
print(f'o último é: {email[13]}')
# quais vem depois do segundo, excluindo o segundo?
print(f'os que vem depois do segundo são: {email[2:]}')
# Quais são todos os caracteres dessa string?
print(f'A sequência todos os caracteres dessa string é: {email[:]}')
# Buscar e imprimir todos os caracteres até o caracter de índice 4 (todos os caracteres antes do @ até o @ incluindo o @)
print(f'A sequência caracteres dessa string até o índice 4 é: {email[:5]}')
# Como acessar o último caracter da lista sem contar o tamanho dela (sem usar a função len())?
print(f'O último caracter dessa string é: {email[-1]}')

o quinto caracter é: @
o último é: m
os que vem depois do segundo são: ug@gmail.com
A sequência todos os caracteres dessa string é: doug@gmail.com
A sequência caracteres dessa string até o índice 4 é: doug@
O último caracter dessa string é: m

### **Métodos para Strings**

In [ ]:
# Sinal de (+) para concatenar strings
nome='Marcella'
sobre='Macedo'
print(nome+" "+sobre)

# Converter um numero em string
cpf=0000000000
str(cpf)
print(type(cpf))

# (in) Retorna verdadeiro se um caracter ou sequencia de caracteres for encontrado dentro de uma string
nomen = 'marcella'
testen = 'mar' in nomen
print(f'marcella contém mar: {testen}')

# (not in) Retorna verdadeiro se um caracter ou sequencia de caracteres NÃO for encontrado dentro de uma string
testen = 'Marcella' not in nomen
print(f'marcella não contém Mar: {testen}')

# (len) Contar o número de caracteres de uma string
qtde = len(nome)
print(f'{nome} tem {qtde} caracteres')

### **Métodos específicos**

In [ ]:
# Método para deixar a primeira letra de uma string maiúscula
nomem = 'marcella'
print(nomem)
nomem = nomem.capitalize()
print(nomem)
nomem = nomem.casefold()
print(nomem)

marcella
Marcella
marcella

In [ ]:
# (count) Contar quantas vezes um caracter aparece em uma string
material = 'paralelepípedo'
qtde_p = material.count('p')
print(f'{material} tem {qtde_p} Ps')

paralelepípedo tem 3 Ps

In [ ]:
# (endswith) Verifica se uma string termina com um caracter ou sequencia de caracteres
email = 'doug@gmail.com'
teste_end = email.endswith('gmail.com')
print(teste_end)

True

In [ ]:
# (startswith) Verifica se uma string começa com um caracter ou sequencia de caracteres
email = 'doug@gmail.com'
teste_beg = email.startswith('d')
print(teste_beg)

True

In [ ]:
# (isnumeric) Verifica uma string é formada por número
rg = 'd200250000'
teste_rg=rg.isnumeric()
print(teste_rg)

False

In [ ]:
# (isalpha) Verifica se uma string é formada por letras
rg2 = 'doug'
teste_rg2 = rg2.isalpha()
print(teste_rg2)

True

In [ ]:
# (isalnum) Verifica se uma string é formada por letras ou números
rg3 = 'D'
teste_rg3 = rg3.isalnum()
print(teste_rg3)

True

In [ ]:
# (split) Separa uma string por caracteres específicos, se não for específicado o caracter ela assume espaço como separador
dados = input('informe os valores separados por espaços ')
dados_sep = dados.split()
print(dados_sep)

informe os valores separados por espaços 1 2 3
['1', '2', '3']

In [ ]:
# (strip) elimina caracteres indesejados de uma string, por padrão remove espaços do início e do final da string
autor = ' Douglas '
print(len(autor))
autor = autor.strip()
print(len(autor))

9
7

In [ ]:
# (replace) substitui um caracter por outro
preco = 'R$ 10.50'
print(preco)
preco = preco.replace('.',',')
print(preco)

R$ 10.50
R$ 10,50

In [ ]:
# (title) Coloca a primeira letra de cada palavra em maiúscula
comp = 'douglas almeida ribeiro'
print(comp)
comp = comp.title()
print(comp)

douglas almeida ribeiro
Douglas Almeida Ribeiro

In [ ]:
# (upper) Coloca todas as letras de um texto em maiúsculas
prof = 'douglas'
print(prof)
prof = prof.upper()
print(prof)

douglas
DOUGLAS

## **Revisão**

https://docs.google.com/document/d/11Q07YVsLaWQ7Lu960OCYsDCOF5nqSqL76n1lMEpl710/edit

## **Estruturas de Condição (if, elif, else)**

*   A instrução **"if"** é usada para executar um bloco de código se uma determinada condição for verdadeira.
*   A instrução **"elif"** é uma abreviação de "else if" e permite testar múltiplas condições em sequência. Ela é usada quando há mais de duas possibilidades a serem consideradas.
*   O **"else"** é em conjunto com o **"if"** usado para executar outro bloco de código caso a condição do "if" seja falsa.

### **IF**

In [ ]:
'''
if condição:
  # bloco de código a ser executado se a condição for verdadeira
'''

'\nif condição:\n  # bloco de código a ser executado se a condição for verdadeira\n'

In [ ]:
idade=19
if idade >=18:    # : faça alguma coisa
    print("Você é maior de idade.")

Você é maior de idade.

In [ ]:
idade=18
if idade >=18:
    print("Você é maior de idade.")

Você é maior de idade.

In [ ]:
idade=17
if idade >=18:
    print("Você é maior de idade.")

### **ELSE**

In [ ]:
'''
if condição:
  # bloco de código caso verdadeiro
else:
  # bloco de código caso if falso
'''

'\nif condição:\n  # bloco de código caso verdadeiro\nelse:\n  # bloco de código caso if falso\n'

In [ ]:
idade = int(input('Digite sua idade: '))

if idade >=18:
  print("Você é maior de idade.")
else:
  print("Você é menor de idade.")

Digite sua idade: 28
Você é maior de idade.

### **ELIF**

In [ ]:
'''
if condição1:
    # bloco de código a ser executado se a condição1 for verdadeira
elif condição2:
    # bloco de código a ser executado se a condição2 for verdadeira
else:
    # bloco de código a ser executado se nenhuma das condições anteriores for verdadeira
'''

'\nif condição1:\n    # bloco de código a ser executado se a condição1 for verdadeira\nelif condição2:\n    # bloco de código a ser executado se a condição2 for verdadeira\nelse:\n    # bloco de código a ser executado se nenhuma das condições anteriores for verdadeira\n'

In [ ]:
nota = float(input('Digite sua nota: '))

if nota >= 90:
    print("Sua nota é A")
elif nota >= 80:
    print("Sua nota é B")
elif nota >= 70:
    print("Sua nota é C")
else:
    print("Sua nota é D")

Digite sua nota: 5
Sua nota é D

### **Exemplo**
Escreva um programa que verifique se um número digitado pelo usuário é positivo, negativo ou zero.
Passo a passo:

1. Solicite ao usuário que digite um número.
2. Armazene o número digitado em uma variável chamada "numero".
3. Verifique se o número digitado é igual a zero. Se sim, exiba a mensagem "O número digitado é zero."
4. Caso contrário, verifique se o número é maior que zero. Se sim, exiba a mensagem "O número digitado é positivo."
5. Se nenhuma das condições anteriores for atendida, significa que o número é negativo. Nesse caso, exiba a mensagem "O número digitado é negativo."
6. Encerre o programa.

In [ ]:
numero = float(input("Digite um número: "))

if numero == 0:
    print("O número digitado é zero.")
elif numero > 0:
    print("O número digitado é positivo.")
else:
    print("O número digitado é negativo.")

Digite um número: 5
O número digitado é positivo.

### **Exercícios da Estrutura de Condição (aula 15)**



1.   Faça um algoritmo que leia um número inteiro e diga se ele é maior, menor ou igual a 10;
2.   Faça um algoritmo que leia dois números inteiros e apresente na tela o maior deles ous se eles são iguais;
3.   Crie um algoritmo que leia um número e diga se ele está no intervalo fechado entre 25 e 200.
4.   Crie um algoritmo que leia um número e informe na tela se o mesmo é positivo. Caso seja, mostre o número na tela;
5.   Crie um algoritmo que leia um número e informe se ele é divisível por 7.
6.   Crie um algoritmo que leia um número e diga se ele é par ou ímpar.
7.   Escreva um programa em Python que solicite ao usuário que digite uma letra. Em seguida, verifique se a letra digitada é uma vogal ou não.
8.   Escreva um programa que solicite ao usuário três notas de um aluno e calcule a média. Em seguida, exiba a média e uma mensagem informando se o aluno foi aprovado (média >=7) ou reprovado.
9.   Escreva um programa que solicite ao usuário os comprimentos dos três lados de um triângulo. Em seguida, exiba uma mensagem informando se o triângulo é equilátero (todos lados iguais), isósceles (dois lados iguais) ou escaleno (todos os lados diferentes).
10.   Escreva um programa que solicite ao usuário sua idade e exiba uma mensagem informando em qual faixa etária ele se encontra: criança (0-12 anos), adolescente (13-17 anos), adulto (18-59 anos) ou idoso (60 anos ou mais).

In [ ]:
# 1.Faça um algoritmo que leia um número inteiro e diga se ele é maior, menor ou igual a 10.

n1 = int(input("Digite um número inteiro: "))

if n1 > 10:
    print("O número é maior que 10.")
elif n1 < 10:
    print("O número é menor que 10.")
elif n1==10:
    print("O número é igual a 10.")

Digite um número inteiro: 10
O número é igual a 10.

In [ ]:
# 2.Faça um algoritmo que leia dois números inteiros e apresente na tela o maior deles ous se eles são iguais.

n2 = int(input("Digite um número: "))
n3 = int(input("Digite outro número: "))

if n2 > n3:
    print(f"O maior número é o {n2}.")
elif n2 < n3:
    print(f"O maior número é o {n3}.")
elif n2==n3:
    print("Os números são iguais.")

Digite um número: 5
Digite outro número: 6
O maior número é o 6.

In [ ]:
# 3.Crie um algoritmo que leia um número e diga se ele está no intervalo fechado entre 25 e 200.

num3 = float(input("Digite um número: "))

if num3 >=25 and num3 <=200:
  print("O número está entre 25 e 200.")
else:
  print("ERROR")

Digite um número: 30
O número está entre 25 e 200.

In [ ]:
# 4.Crie um algoritmo que leia um número e informe na tela se o mesmo é positivo. Caso seja, mostre o número na tela.

n4 = float(input("Digite um número: "))

if n4>=0:
  print(f'O número {n4} é positivo.')
else:
  print(f'O número {n4} é negativo.')

Digite um número: 8
O número 8.0 é positivo.

In [ ]:
# 5.Crie um algoritmo que leia um número e informe se ele é divisível por 7.

n5 = float(input('Digite um número: '))

if n5 % 7 == 0:
  print(f'{n5} é divisível por 7.')
else:
  print("O número não é divisível por 7.")

Digite um número: 49
49.0 é divisível por 7.

In [ ]:
# 6.Crie um algoritmo que leia um número e diga se ele é par ou ímpar.

n6 = float(input("Digite um número: "))

if n6 % 2 == 0 and n6 != 0:
  print(f'O número {n6} é par.')
else:
  print(f'O número {n6} é ímpar.')

Digite um número: 6
O número 6.0 é par.

In [ ]:
# 7.Escreva um programa em Python que solicite ao usuário que digite uma letra. Em seguida, verifique se a letra digitada é uma vogal ou não.

letra7 = input("Digite uma letra: ")

if letra7 == 'a' or letra7=='e' or letra7=='i' or letra7=='o' or letra7=='u':
  print(f'"{letra7}" é uma vogal')
else:
  print(f'"{letra7}" é uma consoante.')

Digite uma letra: a
"a" é uma vogal

In [ ]:
# 8.Escreva um programa que solicite ao usuário três notas de um aluno e calcule a média. Em seguida, exiba a média e uma mensagem informando se o aluno foi aprovado (média >=7) ou reprovado.

aluno = input("Digite o nome do aluno: ")
n81 = float(input("Digite a primeira nota: "))
n82 = float(input("Digite a segunda nota: "))
n83 = float(input("Digite a terceira nota: "))

media = (n81+n82+n83)/3
print(f'A média das notas de {aluno} é: {media:.2f}.')
if media>=7:
  print(f'{aluno} está aprovado(a)! 😎')
else:
  print(f'{aluno} está reprovado(a). 😥')

Digite o nome do aluno: 8
Digite a primeira nota: 7
Digite a segunda nota: 6
Digite a terceira nota: 5
A média das notas de 8 é: 6.00.
8 está reprovado(a). 😥

In [ ]:
# 9.Escreva um programa que solicite ao usuário os comprimentos dos três lados de um triângulo.
#Em seguida, exiba uma mensagem informando se o triângulo é:
#equilátero (todos lados iguais)
#isósceles (dois lados iguais)
#escaleno (todos os lados diferentes)

print("Informe os lados dos triângulo!")
tri1= float(input("Digite o tamanho do lado 1 em cm: "))
tri2= float(input("Digite o tamanho do lado 2 em cm: "))
tri3= float(input("Digite o tamanho do lado 3 em cm: "))

if tri1 <(tri2+tri3) and tri2<(tri1+tri3) and tri3<(tri1+tri2):
  print("Triângulo válido!")
  if tri1 == tri2 == tri3:
    print("O triângulo é equilátero.")
  elif tri1 == tri2 or tri2 == tri3 or tri1 == tri3:
    print("O triãngulo é isósceles.")
  else:
    print("O triângulo é escaleno.")
else:
  print("Triângulo inválido.")

Informe os lados dos triângulo!
Digite o tamanho do lado 1 em cm: 5
Digite o tamanho do lado 2 em cm: 4
Digite o tamanho do lado 3 em cm: 3
Triângulo válido!
O triângulo é escaleno.

In [ ]:
# 10.Escreva um programa que solicite ao usuário sua idade e exiba uma mensagem informando em qual faixa etária ele se encontra:
# criança (0-12 anos)
# adolescente (13-17 anos)
# adulto (18-59 anos)
# idoso (60 anos ou mais)

idade = int(input("Digite sua idade: "))

if idade >= 60:
  print('Você é idoso 👵')
elif idade >=18:
  print('Você é adulto 👩')
elif idade >=13:
  print('Você é adolescente 😎')
else:
  print('Você é criança 🧒')

Digite sua idade: 28
Você é adulto 👩

## **Estruturas de Dados - parte 1 - Listas**

Aula 16

*   **Lista** é uma estrutura que pode armazenar diversos valores sobre um determinado atributo

In [ ]:
lista_vazia = []
noivo = ['Zé','Mané','Ana','Fran','João','Franz']
print(f'Convidados do noivo - {noivo}')
idades = [41, 47, 46, 28, 17, 50]
print(f'Idades dos convidados do noivo {idades}')
massas = [86, 74, 52, 47, 90, 110]
print(f'Massas dos convidados do noivo {massas}')
alturas = [1.68, 1.74, 1.65, 1.65, 1.80, 1.97]
print(f'Alturas (em metros) dos convidados do noivo {alturas}')

Convidados do noivo - ['Zé', 'Mané', 'Ana', 'Fran', 'João', 'Franz']
Idades dos convidados do noivo [41, 47, 46, 28, 17, 50]
Massas dos convidados do noivo [86, 74, 52, 47, 90, 110]
Alturas (em metros) dos convidados do noivo [1.68, 1.74, 1.65, 1.65, 1.8, 1.97]

In [ ]:
print(f'Idades dos convidados do noivo {idades}')

Idades dos convidados do noivo [41, 47, 46, 28, 17, 50]

In [ ]:
# Acessando um elemento específico da lista a partir do seu índice
print(f'A convidada de honra é {noivo[3]}')

# Criar uma sublista com apenas os os três primeiros elementos da lista noivo
sublista = noivo[:3]
print(sublista)
p_u = [noivo[0], noivo[-1]]
print(f'O primeiro convidado é {p_u[0]} e o último convidado é {p_u[-1]}')
print(f'{noivo}')

A convidada de honra é Fran
['Zé', 'Mané', 'Ana']
O primeiro convidado é Zé e o último convidado é Franz
['Zé', 'Mané', 'Ana', 'Fran', 'João', 'Franz']

In [ ]:
# Método index(valor procurado, índice de ínicio da procura, e índice fim da procura) por definição se não for oferecido o índice de ínicio e fim será procurado na lista toda
id = noivo.index('Fran')

In [ ]:
# Qual é o IMC da convidada Fran
print(f'O IMC da Fran é {(massas[id]/alturas[id]**2):.2f}')

O IMC da Fran é 17.26

**Desafio 1:**
Crie um programa que receba um nome e cheque se está na lista. Utilize para buscar massa e altura correspondente, assim como calcular IMC.
Após isso informar ao usuário:

**.index() - consulta argumento e procura o índice correspondente na lista**

In [ ]:
idades = [41, 47, 46, 28, 17, 50]
massas = [86, 74, 52, 47, 90, 110]
alturas = [1.68, 1.74, 1.65, 1.65, 1.80, 1.97]
noivo = ['Zé','Mané','Ana','Fran','João','Franz']         # Cria o banco de dados com os nomes dos convidados do noivo

nome = input('Informe o nome que deseja consultar: ')     # Recebe o nome do usuário
nome = nome.capitalize()                                  # Deixo o nome que o usuário digitou com a primeira letra em caixa alta e as demais em caixa baixa
if nome in noivo:                                         # se o nome que o usuário digitou estiver no banco de dados faça algo
  id2 = noivo.index(nome)                                 # recebendo o argumento nome e procurando o seu índice já sabendo que ele está na lista exatamente com a mesma grafia
  imc = massas[id2]/alturas[id2]**2                       # calculando o imc já sabendo a posição que deve buscar em cada lista (massas e alturas)
  print(f'{nome} tem {massas[id2]} kg, {alturas[id2]} metros e seu IMC é: {imc:.1f}')        # Mostrando o nome digitado e sua massa, altura e IMC.
else:
  print(f'Desculpe, {nome} não está na lista, por favor reinicie o programa para consultar outro nome')

Informe o nome que deseja consultar: zé
Zé tem 86 kg, 1.68 metros e seu IMC é: 30.5

### **Lista vazia e adição de elementos - .append(), .insert() e .pop()**

* Posiciona o elemento criado na última posição

**.append()**

In [ ]:
# Criar lista vazia
d = []

In [ ]:
# Adicionar elemento
d.append(22)
d.append(28)
d.append(27)
d.append(6)

In [ ]:
print(d)

[22, 28, 27, 6]

In [ ]:
lista_vazia = []                # cria uma lista vazia com o nome lista vazia e apaga todos os elementos de qualquer objeto com o mesmo nome
print(lista_vazia)              # imprime uma lista vazia que já existe
lista_vazia.append('Joana')     # adiciona Joana na última posição de uma lista que já exista
lista_vazia.append('Douglas')
lista_vazia.append('Eduardo')
lista_vazia.append('Ester')
lista_vazia.append('Daniela')
lista_vazia.append('Pedro')
lista_vazia.append('Maria')
print(lista_vazia)              # imprime o status atual da lista vazia
fam = lista_vazia
print(lista_vazia)
print(fam)

[]
['Joana', 'Douglas', 'Eduardo', 'Ester', 'Daniela', 'Pedro', 'Maria']
['Joana', 'Douglas', 'Eduardo', 'Ester', 'Daniela', 'Pedro', 'Maria']
['Joana', 'Douglas', 'Eduardo', 'Ester', 'Daniela', 'Pedro', 'Maria']

**.insert( ) - escolhe a posição onde o elemento será inserido**

In [ ]:
# fam.insert - Escolhe a posição onde o elemento será inserido

fam.insert(4, 'Tobias')
print(fam)

['Joana', 'Douglas', 'Eduardo', 'Ester', 'Tobias', 'Daniela', 'Pedro', 'Maria']

**lista[  ] - atribuição direta**

Substitui um elemento no índice escolhido por outro

In [ ]:
fam[3] = 'Raimundo'           # Atribuição direta insere um novo elemento substituindo o anterior se houver
print(fam)

['Joana', 'Douglas', 'Eduardo', 'Raimundo', 'Tobias', 'Daniela', 'Pedro', 'Maria']

**.pop( ) - excluir elementos de uma lista pelo índice**

*   lista.pop() - por padrão exclui o último elemento
*   lista.pop(1) - exclui elemento no índice escolhido

In [ ]:
fam.pop()
print(fam)

['Joana', 'Douglas', 'Eduardo', 'Raimundo', 'Tobias', 'Daniela', 'Pedro']

In [ ]:
# Excluir Joana da lista fam

fam.pop(0)
print(fam)

['Douglas', 'Eduardo', 'Raimundo', 'Tobias', 'Daniela', 'Pedro']

### **Comandos de Organização e Manipulação de listas**

Aula 17

**.remove( ) - excluir elementos de uma lista pelo nome**

In [ ]:
# criando uma lista com nomes
nomes = ['Douglas','Daniela','Pedro','Maria','Eduardo','Ester']

# criando uma lista com números inteiros
pesos = [78,25,98,63,92,67]

# criando uma lista com números decimais
alturas = [1.85,1.29,1.75,1.67,1.82,1.70]

In [ ]:
# forçando um erro usando o remove
nomes.remove('xerox')

ValueError: ignored

In [ ]:
# solução 1

teste = input('Informe o nome que deseja excluir da lista: ')
teste = teste.capitalize()
if teste in nomes:
  nomes.remove(teste)
  print(f'O nome {teste} foi excluído com sucesso.')
else:
  print(f'O nome {teste} não está na lista, logo não pode ser excluído.')

Informe o nome que deseja excluir da lista: zé
O nome Zé não está na lista, logo não pode ser excluído.

**TRY/EXCEPT:**

*  Trata qualquer erro que possa ocorrer e fuja da regra que estipulei

In [ ]:
# solução 2 (utilizando try/except)

teste2 = input('Informe o nome que deseja excluir da lista: ')
teste2 = teste2.capitalize()                                                     # primeira letra maiúscula
try:                                                                             # tentar fazer ação
  nomes.remove(teste2)                                                           # ação caso teste seja bem sucedido
  print(f'O nome {teste2} foi excluído com sucesso.')
except:
  print(f'O nome {teste2} não está na lista, logo não pode ser excluído.')       # ação caso teste falhe

Informe o nome que deseja excluir da lista: zé
O nome Zé não está na lista, logo não pode ser excluído.

In [ ]:
try:
  ida = int(input('Informe sua idade em anos: '))
  if ida >= 18:
    print('maior de idade')
  elif ida < 0:
    print('você digitou uma idade negativa é isso mesmo? ')
  else:
    print('menor de idade')
except:
  print('você não informou um número, por favor reinicie o código e digite um número')

Informe sua idade em anos: 28
maior de idade

**len(), max(), min(), sum(), .count(), .sort(), .sort(reverse=True)**

In [ ]:
# criando uma lista com strings
nomes = ['Douglas', 'Daniela', 'Pedro', 'Maria', 'Eduardo', 'Ester']

# criando uma lista com números inteiros
pesos = [78, 25, 98, 63, 92, 67]

# criando uma lista com números fracionários
alturas = [1.85, 1.29, 1.75, 1.67, 1.82, 1.70]

# Tamanho da lista (len)
print(len(nomes))

# Maior valor da lista
print(max(pesos))

# Menor valor da lista
print(min(alturas))

# Soma dos valores de uma lista
print(sum(alturas))

# Contando a frequência de um valor em uma lista
print(nomes.count('Douglas'))

# Ordenar uma lista crescente
nomes.sort()
print(nomes)

# Ordenar uma lista decrescente
nomes.sort(reverse=True)
print(nomes)

6
98
1.29
10.08
1
['Daniela', 'Douglas', 'Eduardo', 'Ester', 'Maria', 'Pedro']
['Pedro', 'Maria', 'Ester', 'Eduardo', 'Douglas', 'Daniela']

**.extend() - Adiciona elementos de uma lista em outra**

*  Melhor para alteração no banco de dados

In [ ]:
nomes1 = ['Zé','Mané']
nomes2 = ['Ana','José']

nomes1.extend(nomes2)

print(nomes1)

['Zé', 'Mané', 'Ana', 'José']

**(+) - Adiciona todos os elementos de uma lista em outra (concatenando listas)**
* Melhor para filtro:

In [ ]:
nomes1 = ['Zé', 'Mané']
nomes2 = ['Ana', 'José']

teste = nomes1 + nomes2
print(teste)

['Zé', 'Mané', 'Ana', 'José']

In [ ]:
# Colocando uma lista dentro de outra
carros = ['Fusca', 'Gol']
carros2 = ['Uno', 'Punto', 'Bravo']
carros.append(carros2)
print(carros)

['Fusca', 'Gol', ['Uno', 'Punto', 'Bravo']]

In [ ]:
# Filtrando uma lista da outra
fiat = carros[2]
print(fiat)

['Uno', 'Punto', 'Bravo']

In [ ]:
# Filtrando um item de uma lista que está dentro de outra
ok = carros[2][0]
print(f'O melhor carro de todos os tempos é {ok}.')

O melhor carro de todos os tempos é Uno.

**Range**

In [ ]:
# Função range com um argumento cria um lista com n valores inteiros de 0 a N-1
lista1 = list(range(5))
print(lista1)

# Função range com dois argumentos cria um lista com N valores inteiros do início informado no primeiro argumento
# até ((n-1) - primeiro argumento informado) informado no segundo argumento
lista2 = list(range(1,5))
print(lista2)

# Função range com três argumentos cria um lista com definição de
# onde começar (primeiro argumento),
# onde parar (segundo argumento)
# e de qual tamando de intervalo entre os valores (terceiro argumento)
lista3 = list(range(1,5,2))
print(lista3)

[0, 1, 2, 3, 4]
[1, 2, 3, 4]
[1, 3]

## **Estruturas de Repetição (for)**

In [ ]:
# Apresentando e utilizando o for de forma simples

pesos = [78, 25, 98, 63, 92, 67]
for i in pesos:
  print(i)

78
25
98
63
92
67

### **for com else**

In [ ]:
for i in pesos:
    print(i)
else:
    print('Todos os items foram exibidos com sucesso')

78
25
98
63
92
67
Todos os items foram exibidos com sucesso

### **função enumerate**

In [ ]:
notas = [5, 9, 6, 8, 7]

# i = índice
# v = valor

for i, v in enumerate(notas):
  print(i,v)

0 5
1 9
2 6
3 8
4 7

In [ ]:
notas = [5,9,6,8,7]

# Objetivo: percorrer uma lista com notas e para cada valor testar se é >=7
# true=aprovado
# false=reprovado

for i, v in enumerate(notas):
  if notas[i] >= 7:
    print(f'{i}. Aprovado com nota {v}')
  else:
    print(f'{i}. Reprovado com nota {v}')

0. Reprovado com nota 5
1. Aprovado com nota 9
2. Reprovado com nota 6
3. Aprovado com nota 8
4. Aprovado com nota 7

In [ ]:
notas[0]

### **for com range**

In [ ]:
# Utilizando o for com range
pesos = [78, 25, 98, 63, 92, 67]
alturas_quad = []
imc = []
for i in range(len(pesos)):
  print(i)
  alturas_quad.append(alturas[i]**2)
  imc.append(pesos[i]/alturas_quad[i])
print(f'IMC {imc}')

0
1
2
3
4
5
IMC [22.79035792549306, 15.023135628868456, 32.0, 22.589551436050055, 27.77442337881898, 23.18339100346021]

In [ ]:
# Utilizando o for com range
alturas = [1.85, 1.29, 1.75, 1.67, 1.82, 1.70]
alturas_quad = []
imc = []
for i in range(len(alturas)):
  print(f'Posição (índice){i}')
  print(f'Valor {alturas[i]}')
  #alturas_quad.append(alturas[i]**2)
  #imc.append(pesos[i]/alturas_quad[i])
#print(f'IMC {imc}')

Posição (índice)0
Valor 1.85
Posição (índice)1
Valor 1.29
Posição (índice)2
Valor 1.75
Posição (índice)3
Valor 1.67
Posição (índice)4
Valor 1.82
Posição (índice)5
Valor 1.7

In [ ]:
# Utilizando o for com range
alturas = [1.85, 1.29, 1.75, 1.67, 1.82, 1.70]
alturas_quad = []
imc = []
for i in range(6):
  print(f'Posição (índice){i}')
  print(f'Valor {alturas[i]}')
  #alturas_quad.append(alturas[i]**2)
  #imc.append(pesos[i]/alturas_quad[i])
#print(f'IMC {imc}')

Posição (índice)0
Valor 1.85
Posição (índice)1
Valor 1.29
Posição (índice)2
Valor 1.75
Posição (índice)3
Valor 1.67
Posição (índice)4
Valor 1.82
Posição (índice)5
Valor 1.7

### **for com enumerate**

In [ ]:
# Utilizando o for com enumerate
alturas_quad = []
imc = []
for i, v in enumerate(pesos):
  print(i,':',v)
  alturas_quad.append(alturas[i]**2)
  imc.append(pesos[i]/alturas_quad[i])
print(f'IMC {imc}')

0 : 78
1 : 25
2 : 98
3 : 63
4 : 92
5 : 67
IMC [22.79035792549306, 15.023135628868456, 32.0, 22.589551436050055, 27.77442337881898, 23.18339100346021]

### **Exercícios de Fundamentos de Python**

1 - Crie um script que receba do usuário uma lista de n números inteiros digitados pelo usuário na mesma caixa de entrada separados por espaços e após isso utilize o método split para separar esses números e armazená-los em uma lista acesse o índice 0 dessa nova lista e verifique seu tipo e caso seja o tipo inteiro imprima para o usuário a seguinte mensagem: este valor é do tipo inteiro, caso contrário imprima: este valor não é do tipo inteiro.

2 - Crie um script que aproveite a lista utilizada para imprimir a mensagem do exercício anterior e utilize uma estrutura for que percorra toda a lista e faça a tipagem de cada valor como inteiro, após isso
acesse o índice 0 dessa nova lista e verifique seu tipo e caso seja o tipo inteiro imprima para o usuário a seguinte mensagem: este valor é do
tipo inteiro, caso contrário imprima: este valor não é do tipo inteiro.

3 - Utilizando a lista tipada como int do exercício 2, faça um print que exiba a soma de todos os valores dessa lista.

4 - Crie uma lista vazia denominada quadrados e utilizando a lista tipada como int do exercício 2, faça uma estrutura do tipo for que percorra cada elemento dessa lista de números inteiros, eleve cada valor encontrado ao quadrado e insira cada resultado na lista quadrados e ao final exiba a soma dos valores da lista quadrados.

5 - Crie um programa que receba do usuário duas listas de n números inteiros digitados pelo usuário separados por espaços e após isso utilize o método split para dividir cada lista gerando duas novas listas chamadas x e y é importante deixar claro para o usuário que as duas listas digitadas devem ter a mesma quantidade de números digitados
independente de quantos sejam. Após isso, faça a tipagem de todos os números das duas listas como float, então crie três novas listas vazias: xquad, yquad e xy. Agora preencha a lista xquad com cada elemento da lista x elevado ao quadrado, depois faça o mesmo para yquad, elevando cada elemento de y ao quadrado e por último preencha
a lista xy fazendo a multiplicação de cada valor da lista x pelo seu correspondente na lista y. No final crie a variável sx que recebe a soma dos valores da lista x, a variável sy que recebe a soma dos valores da lista y, a variável sxquad, que recebe a soma da lista
xquad, a variável syquad que recebe a soma da lista de yquad e a variável sxy que recebe a soma da lista de xy e no final imprima todas as variáveis de soma criadas.

In [ ]:
# 1.
# Crie um script que receba do usuário uma lista de n números inteiros digitados na mesma caixa separados por espaços
# Após isso utilize o método split para separar esses números
# armazená-los em uma list
# acesse o índice 0 dessa nova lista
# verifique seu tipo
# caso seja o tipo inteiro: imprima: este valor é do tipo inteiro,
# caso contrário imprima: este valor não é do tipo inteiro.

lista=input('Digite números inteiros separando com espaço: ')
print(lista)

lista1=lista.split()
print(lista1)
print(f'O número no índice 0 é {lista1[0]}.')

if type(lista1[0]) == int:
  print('este valor é do tipo inteiro.')
else:
  print('este valor não é do tipo inteiro.')

Digite números inteiros separando com espaço: 1 2 3 4 5
1 2 3 4 5
['1', '2', '3', '4', '5']
O número no índice 0 é 1.
este valor não é do tipo inteiro.

In [ ]:
# 2.
# Crie um script que aproveite a lista utilizada
# Imprimir a mensagem do exercício anterior
# Utilize uma estrutura "for" que percorra toda a lista
# Faça a tipagem de cada valor como inteiro,
# Após isso acesse o índice 0 dessa nova lista
# Verifique seu tipo
# caso seja o tipo inteiro imprima: este valor é do tipo inteiro,
# caso contrário imprima: este valor não é do tipo inteiro.

print(lista1)
convert=[]
for i in range(len(lista1)):
  convert.append(lista1[i])
  convert[i] = int(convert[i])
  print(type(convert),convert)

if type(convert[0]) == int:
  print(f'este valor {convert[0]} é do tipo inteiro.')
else:
  print(f'este valor {convert[0]} não é do tipo inteiro.')

['1', '2', '3', '4', '5']
<class 'list'> [1]
<class 'list'> [1, 2]
<class 'list'> [1, 2, 3]
<class 'list'> [1, 2, 3, 4]
<class 'list'> [1, 2, 3, 4, 5]
este valor 1 é do tipo inteiro.

In [ ]:
# 3.
# Utilizando a lista tipada como int do exercício 2
# Faça um print que exiba a soma de todos os valores dessa lista.

print(convert)
print(f'A soma dos dados da lista é {sum(convert)}.')

[1, 2, 3, 4, 5]
A soma dos dados da lista é 15.

In [ ]:
# 4.
# Crie uma lista vazia denominada quadrados
# utilizando a lista tipada como int do exercício 2
# faça uma estrutura do tipo for que percorra cada elemento dessa lista de números inteiros
# eleve cada valor encontrado ao quadrado
# insira cada resultado na lista quadrados
# exiba a soma dos valores da lista quadrados.

quadrados=[]
print(convert)

for i in range(len(convert)):
  quadrados.append(convert[i])
  quadrados[i]=quadrados[i]**2
  print(f'O item {[i]}:{convert[i]} ao quadrado é: {quadrados[i]}.')

print(f'A soma dos valores é {sum(quadrados)}.')

[1, 2, 3, 4, 5]
O item [0]:1 ao quadrado é: 1.
O item [1]:2 ao quadrado é: 4.
O item [2]:3 ao quadrado é: 9.
O item [3]:4 ao quadrado é: 16.
O item [4]:5 ao quadrado é: 25.
A soma dos valores é 55.

#### Exercício 5 - Pearson

In [ ]:
# 5.
# Crie um programa que receba do usuário duas listas de n números inteiros digitados pelo usuário separados por espaços
# Após isso utilize o método split para dividir cada lista gerando duas novas listas chamadas x e y
# é importante deixar claro para o usuário que as duas listas digitadas devem ter a mesma quantidade de números digitados
# independente de quantos sejam.
# faça a tipagem de todos os números das duas listas como float
# crie três novas listas vazias: xquad, yquad e xy.
# Agora preencha a lista xquad com cada elemento da lista x elevado ao quadrado
# faça o mesmo para yquad, elevando cada elemento de y ao quadrado
# por último preencha a lista xy fazendo a multiplicação de cada valor da lista x pelo seu correspondente na lista y
# No final crie a variável sx que recebe a soma dos valores da lista x
# variável sy que recebe a soma dos valores da lista y
# variável sxquad, que recebe a soma da lista xquad,
# variável syquad que recebe a soma da lista de yquad
# variável sxy que recebe a soma da lista de xy
# imprima todas as variáveis de soma criadas.

n1=input('Digite uma lista de números separando por espaço: ')
n2=input('Digite outra lista com a mesma qtd de números separando por espaço: ')

x = n1.split()
y = n2.split()

print(f'lista 1:{x}, {len(x)} valores')
print(f'lista 2:{y}, {len(y)} valores')

xquad=[]
yquad=[]
xy=[]

 # Checando se as listas tem a mesma quantidade de valores:

if len(x) == len(y):
  for i in range(len(x)):
    x[i]=float(x[i])
    y[i]=float(y[i])
    xquad.append(x[i]**2)
    yquad.append(y[i]**2)
    xy.append(x[i]*y[i])

  print(f'xquad:{xquad}')
  print(f'yquad:{yquad}')
  print(f'xy:{xy}')

  sx=sum(x)
  sy=sum(y)
  sxquad=sum(xquad)
  syquad=sum(yquad)
  sxy=sum(xy)

  print(f'A soma de x é {sx}.')
  print(f'A soma de y é {sy}.')
  print(f'A soma de xquad é {sxquad}.')
  print(f'A soma de yquad é {syquad}.')
  print(f'A soma de xy é {sxy}.')

# Adicionando a fórmula de Pearson a questão:

  pearson= (len(x)*sxy-sx*sy)/((len(x)*sxquad-sx**2)*(len(x)*syquad-sy**2))**0.5
  print(f'O coeficiente de correlação de Pearson é: {pearson}.')

else:
  print('As listas têm tamanhos diferentes, execute o código novamente.')

Digite uma lista de números separando por espaço: 1 2 3
Digite outra lista com a mesma qtd de números separando por espaço: 1 2 3
lista 1:['1', '2', '3'], 3 valores
lista 2:['1', '2', '3'], 3 valores
xquad:[1.0, 4.0, 9.0]
yquad:[1.0, 4.0, 9.0]
xy:[1.0, 4.0, 9.0]
A soma de x é 6.0.
A soma de y é 6.0.
A soma de xquad é 14.0.
A soma de yquad é 14.0.
A soma de xy é 14.0.
O coeficiente de correlação de Pearson é:1.0.

### **Loop While**

In [ ]:
c=0
v=[2,4]
n=int(input('Informe quantos vezes repetir a msg: '))
while c < n:
  v.append(v[0]**v[1])
  print(f'A lista é: {v}')
  print(f'Soma da lista v = {sum(v)}.')
  c += 1

Informe quantos vezes repetir a msg: 2
A lista é: [2, 4, 16]
Soma da lista v = 22.
A lista é: [2, 4, 16, 16]
Soma da lista v = 38.

Faça um script que receba do usuário cinco números inteiros, armazene os
números recebidos em uma lista e no final exiba a soma desses valores

In [ ]:
n1 = int(input('Informe o 1º número inteiro: '))
n2 = int(input('Informe o 2º número inteiro: '))
n3 = int(input('Informe o 3º número inteiro: '))
n4 = int(input('Informe o 4º número inteiro: '))
n5 = int(input('Informe o 5º número inteiro: '))
numeros = [n1, n2, n3, n4, n5]
print(f'A soma dos números digitados é: {sum(numeros)} ')

Faça um script que receba do usuário cinco números inteiros, armazene os
números recebidos a cada momento em que forem recebidos em uma lista e
no final exiba a soma desses valores.

In [ ]:
numeros = []
n1 = int(input('Informe o 1º número inteiro: '))
numeros.append(n1)
n2 = int(input('Informe o 2º número inteiro: '))
numeros.append(n2)
n3 = int(input('Informe o 3º número inteiro: '))
numeros.append(n3)
n4 = int(input('Informe o 4º número inteiro: '))
numeros.append(n4)
n5 = int(input('Informe o 5º número inteiro: '))
numeros.append(n5)

print(f'A soma dos números digitados é: {sum(numeros)} ')

Escreva um código que receba do usuário 5 números inteiros e armazene os números em uma lista depois exiba a soma dos valores.

In [ ]:
# Escreva um código que receba do usuário 5 números inteiros
# Armazene os números em uma lista
# Exiba a soma dos valores

numeros=input('Digite 5 números inteiros separados por espaço: ')
g=numeros.split()
print(g)
print(type(g[i]))
g[i]=int(g[i])

Digite 5 números inteiros separados por espaço: 1 2 3 4 5
['1', '2', '3', '4', '5']

Faça um script que receba n números inteiros um por um e armazene os números recebidos a cada momento em uma lista. Exiba a soma desses valores sem utilizar o while.

In [ ]:
# Faça um script que receba n números inteiros um por um
# Armazene os números recebidos a cada momento em uma lista
# exiba a soma desses valores
# Utilizar o while

n=0
list=[]
while n>0:
  a=print(input('Digite um número inteiro: '))
  list.append(a)
  n += 1

Faça um programa que receba do usuário números inteiros e os insira na lista somente se o número for ímpar e encerre o programa quando houver 5 números.

In [ ]:
# Faça um programa que receba do usuário números inteiros
# Insira na lista somente se o número for ímpar
# Encerre o programa na contagem de 5 números

## **Funções**

In [ ]:
'''
def nomedafuncao (argumento 1, argumento 2, .... argumento n):
  bloco de código ou bloco de instruções
  return "valor"
'''

In [ ]:
# Exemplo de função sem argumento e sem bloco de código
def teste ():
  return print('Bom dia!')

In [ ]:
# Chamando a função teste criada no bloco anterior
teste()

### Exemplo de função com argumento e bloco de código:
* Crie uma função que receba dois argumentos (x, y) e faça o cálculo de x ** y

In [ ]:
def casamento (x, y):
  vezes = x ** y
  return print(f'O professor douglas casará {vezes} vezes nessa vida')

In [ ]:
# chamando a função utilizando a ordem padrão dos argumentos
casamento(2, 3)

In [ ]:
# Chamando a função invertendo a ordem padrão dos argumentos sem aviso prévio (vai mudar o resultado anterior)
casamento(3, 2)

In [ ]:
# Para inverter a ordem padrão dos argumentos é necessário explicitar os valores dos argumentos
casamento(y=3, x=2)

In [ ]:
# Também é possível ser redundante e respeitar a ordem padrão dos argumentos e explicitar os seus valores
casamento(x=2, y=3)

### Exemplo:

* Elabore uma função que receba do usuário os valores de preço de venda (p),
custo variável (cv), custo fixo (cf) e calcule o valor do ponto de equlíbrio
em quantidade e informe o usuário.

In [ ]:
def peq ():
  p = float(input('Informe o valor do preço unitário de venda em R$: '))
  cv = float(input('Informe o valor do custo variável unitário em R$: '))
  cf = float(input('Informe o valor do custo fixo mensal em R$: '))
  qt = cf/(p - cv)
  return print(f'A partir de aproximadamente {qt:.0f} unidades você terá lucro')

In [ ]:
peq()

### **Exercícios**

**Prazos Médios, Ciclo Operacional e Ciclo de Caixa**

In [ ]:
'''
Elabore uma função que receba em cinco inputs diferentes as seguintes informações:
1 - Receita líquida em R$
2 - Custo em R$
3 - Estoques em R$
4 - Contas a receber em R$
5 - Fornecedores em R$

Após receber as informações acima a função deve calcular o valor e printá-lo dos
seguintes KPIs:

a Prazo médio de estoques - PME
b Prazo médio de Recebimento - PMR
c Prazo médio de Pagamento PMP
d Ciclo operacional - CO
e Ciclo de caixa

E por último:
Se PMP for maior que ciclo operacional print a mensagem essa em média empresa
paga tantos dias depois de receber

Se PMP for menor que ciclo operacional print a mensagem essa em média empresa
paga tantos dias antes de receber

Se PMP for igual ao ciclo operacional print a mensagem essa em média empresa
no mesmo dia em que recebe

'''
def giro():
  receita=float(input('Informe a receita líquida (R$): '))
  custo=float(input('Informe o custo (R$): '))
  estoque=float(input('Informe o valor de estoque (R$): '))
  contas=float(input('Informe as contas a receber (R$): '))
  fornec=float(input('Informe o saldo devedor aos fornecedores (R$): '))
  n=int(input('Informe o período do balanço em dias inteiros: '))

  pme=estoque/custo*n
  pmr=contas/receita*n
  pmp=fornec/custo*n
  co=pme+pmr
  cc=co-pmp

  print(f' O Prazo médio de Estoques é: {pme:.0f} dias.')
  print(f' O Prazo médio de Recebimento é: {pmr:.0f} dias.')
  print(f' O Prazo médio de Pagamento é: {pmp:.0f} dias.')
  print(f' O Ciclo operacional é: {co:.0f} dias.')
  print(f' O Ciclo de caixa é: {cc:.0f} dias.')

  if pmp>co:
    print(f'Em média a empresa paga {abs(cc):.0f} dias depois de receber.')
  elif pmp<co:
    print(f'Em média a empresa paga {abs(cc):.0f} dias antes de receber.')
  else:
    print(f'em média a empresa no mesmo dia em que recebe.')

In [ ]:
giro()

Informe a receita líquida (R$): 10000
Informe o custo (R$): 7000
Informe o valor de estoque (R$): 100
Informe as contas a receber (R$): 100
Informe o saldo devedor aos fornecedores (R$): 600
Informe o período do balanço em dias inteiros: 360
 O Prazo médio de Estoques é: 5 dias.
 O Prazo médio de Recebimento é: 4 dias.
 O Prazo médio de Pagamento é: 31 dias.
 O Ciclo operacional é: 9 dias.
 O Ciclo de caixa é: -22 dias.
Em média a empresa paga 22 dias depois de receber.

**Media, Variância e Desvio Padrão**

In [ ]:
'''
Faça uma função sem parâmetro que ao ser acionada solicite ao usuário uma sequência
númerica em uma única caixa de texto e separada por espaços e então
após o usuário inserir os valores corretos a função devolva um print informando
o valor da média, da variância e do desvio padrão da sequência informada
'''

def medidas_descritivas():
  x=input('Digite números separados por espaço: ')
  x=x.split()

  sub=[]

  for i in range(len(x)):
    x[i]=float(x[i])
  media=sum(x)/len(x)

  for i in range(len(x)):
    sub.append((x[i]-media)**2)

  variancia=sum(sub)/(len(x)-1)
  desvpad=variancia**0.5
  print(f'''As medidas descritivas são:
  média = {media:.2f},
  variância = {variancia:.2f} e
  desvio padrão = {desvpad:.2f}''')

In [ ]:
medidas_descritivas()

Digite números separados por espaço: 1 2 2 3 4 6 7 8 9
Lista:[1.0, 2.0, 2.0, 3.0, 4.0, 6.0, 7.0, 8.0, 9.0].
A média é 4.67
A média é 8.50
A média é 2.92